version: "2"

services:
    ca0:
        image: hyperledger/fabric-ca
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-org1
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.abw.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/598a110f0918c521c9081bce29b18106bbbc6491f710303b5562f6bcc4d963a2_sk
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.abw.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/598a110f0918c521c9081bce29b18106bbbc6491f710303b5562f6bcc4d963a2_sk
        volumes:
            - ./crypto-config/peerOrganizations/org1.abw.com/ca/:/etc/hyperledger-fabric-ca-server-config
        container_name: ca_peerOrg1

    orderer.abw.com:
        container_name: orderer.abw.com
        image: hyperledger/fabric-orderer
        environment:
            - ORDERER_GENERAL_LOGLEVER=debug
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
            # enabled TLS
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        ports:
            - 7050:7050
        volumes:
            - ./crypto-config/ordererOrganizations/abw.com/orderers/orderer.abw.com/msp:/etc/hyperledger/msp/orderer/msp
            - ./crypto-config/ordererOrganizations/abw.com/orderers/orderer.abw.com/msp:/var/hyperledger/orderer/msp
            - ./crypto-config/ordererOrganizations/abw.com/orderers/orderer.abw.com/tls/:/var/hyperledger/orderer/tls
    
    peer0.org1.abw.com:
        container_name: peer0.org1.abw.com
        image: hyperledger/fabric-peer
        environment:
            - CORE_LOGGING_PEER=debug
            - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_ID=peer0.org1.abw.com
            - CORE_PEER_ADDRESS=peer0.org1.abw.com:7051
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=abw_net
            - CORE_PEER_LOCALMSPID=Org1MSP
            - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: peer node start #--peer-defaultchain=false
        ports:
            - 7051:7051
            - 7053:7053
        volumes:
            - ./var/run/:/host/var/run/
            - ./:/etc/hyperledger/configtx
            - ./crypto-config/peerOrganizations/org1.abw.com/peers/peer0.org1.abw.com/msp:/etc/hyperledger/peer/msp
            - ./crypto-config/peerOrganizations/org1.abw.com/users:/etc/hyperledger/msp/users
        depends_on:
            - orderer.abw.com
            - couchdb0

    couchdb0:
        container_name: couchdb0
        image: hyperledger/fabric-couchdb
        ports:
        - 5984:5984
        environment:
            DB_URL: http://localhost:5984/member_db

    peer1.org1.abw.com:
        container_name: peer1.org1.abw.com
        image: hyperledger/fabric-peer
        environment:
            - CORE_LOGGING_PEER=debug
            - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_ID=peer1.org1.abw.com
            - CORE_PEER_ADDRESS=peer1.org1.abw.com:7051
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=abw_net
            - CORE_PEER_LOCALMSPID=Org1MSP
            - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: peer node start #--peer-defaultchain=false
        ports:
            - 8051:7051
            - 8053:7053
        volumes:
            - ./var/run/:/host/var/run/
            - ./:/etc/hyperledger/configtx
            - ./crypto-config/peerOrganizations/org1.abw.com/peers/peer1.org1.abw.com/msp:/etc/hyperledger/peer/msp
            - ./crypto-config/peerOrganizations/org1.abw.com/users:/etc/hyperledger/msp/users
        depends_on:
            - orderer.abw.com
            - couchdb1

    couchdb1:
        container_name: couchdb1
        image: hyperledger/fabric-couchdb
        ports:
        - 6984:5984
        environment:
            DB_URL: http://localhost:6984/member_db